### ISSUE TITLE
Error message in the logs

### ISSUE THREAD

**Issue by notsphinx** [thevoltagesource/eagle-mqtt-bridge#19]
TypeError: Cannot read properties of undefined (reading '0')
    at processNode (/app/eagle-listener.js:101:31)
    at processMessage (/app/eagle-listener.js:36:7)
    at /app/eagle-listener.js:21:6
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)

**Comment by notsphinx** [comment]
This is what the device is sending in NetworkInfo

`<NetworkInfo>
  <DeviceMacId>0xd8d5b90000XXXXXX</DeviceMacId>
  <ExtPanId>0xXXXXXXXXXXXXXXXX</ExtPanId>
  <PanId>0x0a6a</PanId>
  <ShortAddr>0x0000</ShortAddr>
  <Channel>20</Channel>
  <Port>/dev/ttyS2</Port>
  <External>yes</External>
  <Mailbox>ember_c_ttyS2_queue</Mailbox>
  <Protocol>zigbee</Protocol>
</NetworkInfo>`

**Comment by thevoltagesource** [comment]
That looks similar to the NetworkInfo message from the EAGLE-100 but there are a couple of differences in the fields. Do you have the EAGLE 100?  if so, what firmware version is your Eagle on?
